//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int Country_id { get; set; }
        public string Name { get; set; }
        public string Stolitsa { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Cost_people { get; set; }
        public string Continent { get; set; }
    }
}
