//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_discipline { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_prepod { get; set; }
        public string auditoriya { get; set; }
        public Nullable<int> mark { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Student Student { get; set; }
    }
}
