//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YchebnayaEntities : DbContext
    {
        public YchebnayaEntities()
            : base("name=YchebnayaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animals_Safiullin> Animals_Safiullin { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Country_Safiulliun> Country_Safiulliun { get; set; }
        public virtual DbSet<Cveti_Safiullin> Cveti_Safiullin { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Fackultet> Fackultet { get; set; }
        public virtual DbSet<Injener> Injener { get; set; }
        public virtual DbSet<Kafedra> Kafedra { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ypravlenie_Safiulliun> Ypravlenie_Safiulliun { get; set; }
        public virtual DbSet<Zav_kafedroy> Zav_kafedroy { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
        public virtual DbSet<Гимназисты> Гимназисты { get; set; }
    }
}
