//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ypravlenie_Safiulliun
    {
        public int Id { get; set; }
        public string Vieww { get; set; }
    }
}
