//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ychebnaya.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public string Id { get; set; }
        public Nullable<int> Id_disciplina { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
